from web_scraper import __version__
from web_scraper.scraper import get_citations_needed_count,get_citations_needed_report

def test_version():
    assert __version__ == '0.1.0'



def test_get_citations_needed_count():
    count1=get_citations_needed_count('https://en.wikipedia.org/wiki/History_of_chocolate')
    count2= get_citations_needed_count('https://en.wikipedia.org/wiki/History_of_Mexico')
    count3=get_citations_needed_count('https://en.wikipedia.org/wiki/History_of_Jordan')
    assert count1 == 2
    assert count2 == 5
    assert count3 == 4

def test_get_citations_needed_report():
    
    report1= get_citations_needed_report('https://en.wikipedia.org/wiki/History_of_chocolate')
    report2=get_citations_needed_report('https://en.wikipedia.org/wiki/History_of_Jordan')
    report3= get_citations_needed_report('https://en.wikipedia.org/wiki/History_of_Mexico')
    assert report1==['Nature Ecology and Evolution reported probably the earliest cacao use from approximately 5,300 years ago recovered from the Santa Ana (La Florida) site in southeast Ecuador.[8]\nAnother find of chemically traced cacao was in 1984 when a team of archaeologists in Guatemala explored the Mayan site of Río Azul. They discovered fifteen vessels surrounding male skeletons in the royal tomb. One of these vessels was beautifully decorated and covered in various Mayan glyphs. One of these glyphs translated to "kakaw", also known as cacao. The inside of the vessel was lined with a dark-colored powder, which was scraped off for further testing. Once the archaeologists took this powder to the Hershey Center for Health and Nutrition to be tested[citation needed], they found trace amounts of theobromine in the powder, a major indicator of cacao. This cacao was dated to sometime between 460 and 480 AD [9]\n', '\n', "Roughly two-thirds of the world's cocoa is produced in Western Africa, with Ivory Coast being the largest source, producing a total crop of 1,448,992 tonnes.[39] Ghana, Nigeria, and Cameroon are other West African countries among the top 5 cocoa-producing countries in the world. Like many food industry producers, individual cocoa farmers are at the mercy of volatile world markets. The price can vary from between £500 ($945) and £3,000 ($5,672) per ton in the space of just a few years.[citation needed]  While investors trading in cocoa can dump shares at will, individual cocoa farmers can not ramp up production and abandon trees at anywhere near that pace.\n", '\n']
    assert report2==["The city of Saltus was probably established by Alexander the Great. Later antiquity saw the rise of the Nabatean kingdom (Arabic: الأنباط\u200e Al-Anbat)[citation needed] with its capital at Petra, which in time became a border, client state of the Roman Empire that got absorbed into the Empire in 106 CE. During the Greco-Roman period of influence, a number of semi-independent city-states also developed in the region, grouped by general Pompey into a city-league, the Decapolis, including on the territory of modern-day Jordan the cities of Gerasa (Jerash), Philadelphia (Amman), Abila (probably identical with ancient Raphana; today's Quweilbeh), Dion and Capitolias (Beit Ras; possibly the same as ancient Dion, with various identification attempts), Gadara (Umm Qays), and Pella (Tabaqat Fahl, west of Irbid). After the Christianisation of the Roman Empire in the 4th century, historians use the term Byzantine Empire for the eastern realm. The Christian Arab tribe of the Ghassanids ruled Transjordan on behalf of the Byzantines. Many exquisite mosaic floors from churches of the Byzantine period have been unearthed, the best known containing the so-called Madaba Map of the Holy Land.\n", '\n', 'With the break-up of the Ottoman Empire at the end of World War I, the League of Nations and the occupying powers, Britain and France, redrew the borders of the Middle East. Their decisions, most notably the Sykes–Picot Agreement, led to the establishment of the French Mandate for Syria and British Mandate for Palestine. The latter included the territory of Transjordan, which had been allocated to Abdullah I of Jordan approximately a year prior to the finalization of the Mandate document (the Mandate officially introduced in 1923).[citation needed]\n', '\n', 'In 1928, Britain officially provided King Abdullah with full autonomy, though the British RAF continued to provide security to the emirate.[citation needed]\n', '\n']
    assert report3==['The first people to settle in Mexico encountered a climate far milder than the current one. In particular, the Valley of Mexico contained several large paleo-lakes (known collectively as Lake Texcoco) surrounded by dense forest. Deer were found in this area, but most fauna were small land animals and fish and other lacustrine animals were found in the lake region.[citation needed][6] Such conditions encouraged the initial pursuit of a hunter-gatherer existence.\n', '\n', 'The Mexica people arrived in the Valley of Mexico in 1248 AD. They had migrated from the deserts north of the Rio Grande[citation needed] over a period traditionally said to have been 100 years. They may have thought of themselves as the heirs to the prestigious civilizations that had preceded them.[citation needed] What the Aztec initially lacked in political power, they made up for with ambition and military skill. In 1325, they established the biggest city in the world at that time, Tenochtitlan.\n', '\n', 'The Spanish had no intention to turn over Tenochtitlan to the Tlaxcalteca. While Tlaxcalteca troops continued to help the Spaniards, and Tlaxcala received better treatment than other indigenous nations, the Spanish eventually disowned the treaty. Forty years after the conquest, the Tlaxcalteca had to pay the same tax as any other indigenous community.[citation needed]\n', '\n', "During the three centuries of colonial rule, fewer than 700,000 Spaniards, most of them men, settled in Mexico.[citation needed] Europeans, Africans, and indigenous intermixed, creating a mixed-race casta population in a process known as mestizaje. Mestizos, people of mixed European-indigenous ancestry, constitute the majority of Mexico's population.\n", '\n']
 

